paths:
  js: ./build/**/*.js
  coffee: ./src/**/*.coffee
  html: ./src/*.html
  yaml:
    - ./src/**/*.yml
    - ./config.yml
  bootstrap: ./build/app.js
  doc: ./doc
  docsource: ./doc/sources
  nodoc: "nodoc.txt"
  index_file: ./build/index.html
  build: ./build
  karma: ./karma.coffee
  config: ./config.yaml

  scss_bootstrap: ./src/app.scss
  scss: ./src/styles
  images: ./src/images

sass:
  includePaths:
    - ./src/styles
    - ./src/styles/bourbon
    - ./bower_components
    - ./bower_components/bootstrap-sass-official/vendor/assets/stylesheets

cucumber:
  paths:
    features: ./tests/features/**/*.feature
    definitions: ./tests/definitions/**/*.coffee
    support: ./tests/support/**/*.coffee

browserify:
  paths:
    - ./build
    - ./build/framework
    - ./node_modules
    - ./bower_components
    - ./bower_components/react
    - ./bower_components/react-router/dist/
  shim:
    jquery:
      path: ./bower_components/jquery/dist/jquery.js
      exports : jquery
    lodash:
      path: ./bower_components/lodash/dist/lodash.js
      exports : _

api_version: v1

api:
  v1:
    protocol : https
    host     : tm6.infowatch.ru
    path     : /api

shared:
  - api_version
  - api
