################################################################################
# ENVIRONMENT OPTIONS

api_version: v1

api:
  v1:
    protocol: https
    host: v-tavadov-devel
    path: /api

# specify what options will be injected to application bundle
shared:
  - api_version
  - api

################################################################################
# BUILD SYSTEM (GULP) PATHS

paths:

  common: &common
    images     : images/
    modules    : modules/
    components : components/

  # SOURCES
  src:
    << : *common
    base      : src

    scripts   : /**/*.coffee
    configs   : /**/*.yaml
    bootstrap : app.coffee
    index     : index.jade
    styles    : app.scss

    components:
      templates : /**/components/**/*.jade
      styles    : /**/components/**/*.scss

  # COMPILED SOURCES
  compiled:
    << : *common
    base: compiled

    scripts   : /**/*.js
    configs   : /**/*.json
    bootstrap : app.js
    styles    : app.css

    components:
      templates : /**/*-tmpl.js
      styles    : /**/components/**/*.css

  # BUILDED SOURCES
  build:
    << : *common
    base: build

    index     : index.html
    bootstrap : app.js
    styles    : app.css

  # MISC
  config : config.yml
  nodoc  : nodoc.txt
  karma  : karma.coffee

################################################################################
# GENERATORS OPTIONS

templates:
  # using array/object means templates will be processed together
  component:
    - ./templates/component.coffee
    - ./templates/component.scss
    - ./templates/component.jade

################################################################################
# STYLES COMPILATION OPTIONS

scss:
  includePaths:
    # common
    - ./src/styles
    - ./src/styles/bourbon
    # components
    - ./src/components/**/
    - ./src/modules/**/components/**/
    # vendors
    - ./bower_components
    - ./bower_components/bootstrap-sass-official/vendor/assets/stylesheets

################################################################################
# TESTS OPTIONS

cucumber:
  paths:
    features: ./tests/features/**/*.feature
    definitions: ./tests/definitions/**/*.coffee
    support: ./tests/support/**/*.coffee

################################################################################
# CODE COMPILATION OPTIONS

browserify:
  paths:
    # precompiled sources
    - ./compiled
    - ./compiled/framework
    - ./compiled/components/**/
    - ./compiled/modules/**/components/**/
    # vendors
    - ./node_modules
    - ./bower_components
    - ./bower_components/react
    - ./bower_components/**/dist/ # warning, may cause conflicts

# components options
component:
  classNameSuffix: '-component'

################################################################################
# SERVING OPTIONS (DEVELOPMENT ONLY)

# livereload options for
# development web-server
livereload:
  enable: true
  cwd: ./build
  # watch filter
  paths:
    - app.js
    - app.css
    - index.html
    - config.json
