paths:
  js: ./compiled/**/*.js
  coffee: ./src/**/*.coffee
  html: ./src/*.html
  yaml:
    - ./src/**/*.yml
    - ./config.yml
  bootstrap: ./compiled/app.js
  doc: ./doc
  docsource: ./doc/sources
  nodoc: nodoc.txt
  index_file: index.html
  index_path: ./build/index.html
  build: ./build
  src: ./src
  compiled: ./compiled
  karma: ./karma.coffee
  config: ./config.yaml
  jade: ./src/**/*.jade

  modules: ./src/modules
  scss_bootstrap: ./src/app.scss
  scss: ./src/styles/**/*.scss
  images: ./src/images

  # used to split paths with
  components_dir: components

component:
  classNameSuffix: '-component'



templates:
  # using array/object means templates will be processed together
  component:
    - ./templates/component.coffee
    - ./templates/component.scss
    - ./templates/component.jade


scss:
  includePaths:
    - ./src/styles
    - ./src/styles/bourbon
    - ./bower_components
    - ./bower_components/bootstrap-sass-official/vendor/assets/stylesheets

cucumber:
  paths:
    features: ./tests/features/**/*.feature
    definitions: ./tests/definitions/**/*.coffee
    support: ./tests/support/**/*.coffee

livereload:
  enable: true
  cwd: ./build
  paths:
    - app.js
    - app.css
    - index.html
    - config.json

browserify:
  paths:
    - ./compiled
    - ./compiled/framework
    - ./compiled/components/**/ # closing "/" to affect only dirs
    - ./compiled/modules/**/components/**/
    - ./node_modules
    - ./bower_components
    - ./bower_components/react
    - ./bower_components/**/dist/

api_version: v1

api:
  v1:
    protocol: https
    host: v-tavadov-devel
    path: /api

shared:
  - api_version
  - api
